name: mono_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.4
  smooth_page_indicator: ^1.0.0+2
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    # - assets/images/
    - assets/images/splash/splash.svg
    - assets/images/on_boarding/on_boarding_1.svg
    - assets/images/on_boarding/on_boarding_2.svg
    - assets/images/login/phone.svg
    - assets/images/login/Facebook.svg
    - assets/images/login/google.svg
    - assets/images/login/eye_off.svg
    - assets/images/login/mail.svg
    - assets/images/services/living_room.jpg
    - assets/images/services/space_joy.jpg
    - assets/images/services/search.svg
    - assets/images/services/home.svg
    - assets/images/services/briefcase.svg
    - assets/images/services/shopping_cart.svg
    - assets/images/services/user.svg
    - assets/images/services/bell.svg
    - assets/images/services/Vector.svg
    - assets/images/services/ellipse.svg
    - assets/images/services/categories/gardens.svg
    - assets/images/services/categories/electricity.svg
    - assets/images/services/categories/cleaning.svg
    - assets/images/services/categories/plunger.svg
    - assets/images/services/profile/about.svg
    - assets/images/services/profile/address.svg
    - assets/images/services/profile/contact.svg
    - assets/images/services/profile/favorites.svg
    - assets/images/services/profile/setting.svg
    - assets/images/services/profile/share.svg
    - assets/images/services/profile/sign_out.svg
    - assets/images/services/profile/wallet.svg
    - assets/images/services/profile/profile.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500

